### ISSUE TITLE
Missing build instructions?

### ISSUE THREAD

**Issue by thewarpaint** [marcelduran/yslow#131]
After building yslow using `$ make nodeserver` I tried running it with `$ node yslow-server.js` and got the following error:

``` bash
module.js:340
    throw err;
          ^
Error: Cannot find module 'jsdom'
    at Function.Module._resolveFilename (module.js:338:15)
    at Function.Module._load (module.js:280:25)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/Users/egarcia/projects/blog/yslow/build/nodeserver/yslow-server.js:11:11)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Function.Module.runMain (module.js:497:10)
```

This was easy to solve, I just did `$ npm install jsdom`. Then I tried running it again and got the following:

``` bash
Error: Most middleware (like bodyParser) is no longer bundled with Express and must be installed separately. Please see https://github.com/senchalabs/connect#middleware.
    at Function.Object.defineProperty.get (/Users/egarcia/projects/blog/node_modules/express/lib/express.js:89:13)
    at Object.<anonymous> (/Users/egarcia/projects/blog/yslow-server.js:238:17)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Function.Module.runMain (module.js:497:10)
    at startup (node.js:119:16)
    at node.js:906:3
```

Am I doing something wrong? What exactly should I install from [the middleware list](https://github.com/senchalabs/connect#middleware)?

P.S. I think it would really help to have a `package.json` file somewhere so that the dependencies can be installed easily.

**Comment by anands** [comment]
Same problem, any update on this?

**Comment by thewarpaint** [comment]
Last commit was almost a year ago, so I guess no one's maintaining this now. :(

**Comment by anands** [comment]
I tried [installing all packages](https://github.com/senchalabs/connect#middleware),but no luck. This [seems to be working](http://yslow.org/command-line-har/)
