### ISSUE TITLE
junit format results in invalid XML

### ISSUE THREAD

**Issue by jhansche** [marcelduran/yslow#57]
When a page also generates some kind of JavaScript error or warning, the error message is printed to stdout.  If you also requested --format junit, it will then print the XML content after those error messages.  The result is that the XML file cannot be parsed because it begins with non-XML content.  The actual error (in Jenkins) is:

```
Caused by: org.xml.sax.SAXParseException: Content is not allowed in prolog.
    at com.sun.org.apache.xerces.internal.util.ErrorHandlerWrapper.createSAXParseException(Unknown Source)
    at com.sun.org.apache.xerces.internal.util.ErrorHandlerWrapper.fatalError(Unknown Source)
    at com.sun.org.apache.xerces.internal.impl.XMLErrorReporter.reportError(Unknown Source)
    at com.sun.org.apache.xerces.internal.impl.XMLScanner.reportFatalError(Unknown Source)
    at com.sun.org.apache.xerces.internal.impl.XMLDocumentScannerImpl$PrologDriver.next(Unknown Source)
    at com.sun.org.apache.xerces.internal.impl.XMLDocumentScannerImpl.next(Unknown Source)
    at com.sun.org.apache.xerces.internal.impl.XMLNSDocumentScannerImpl.next(Unknown Source)
    at com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl.scanDocument(Unknown Source)
    at com.sun.org.apache.xerces.internal.parsers.XML11Configuration.parse(Unknown Source)
    at com.sun.org.apache.xerces.internal.parsers.XML11Configuration.parse(Unknown Source)
    at com.sun.org.apache.xerces.internal.parsers.XMLParser.parse(Unknown Source)
    at com.sun.org.apache.xerces.internal.parsers.AbstractSAXParser.parse(Unknown Source)
    at com.sun.org.apache.xerces.internal.jaxp.SAXParserImpl$JAXPSAXParser.parse(Unknown Source)
    at org.dom4j.io.SAXReader.read(SAXReader.java:465)
    ... 18 more
```

The problem is that the console messages are not isolated from the output report file.  Is there a way to instead specify the report file via  command line argument, instead of redirecting stdout to the report file?  Or change the console messages to go to stderr, and leave stdout as just the report file.

**Comment by marcelduran** [comment]
Thanks for the catch, I'm about to revisit the output logic in order to add file support. Stay tuned.
